<?php
/**
 * This file contains all Seoul subway stations in Korean and their romanization.
 * Information manually extracted from Wikipedia.
 * In case a 3rd field is included, it marks it doesn't follow pure romanization:
 * it's usually a half-translation or a complex case.
 */
$seoulLines[1] = [
    ['소요산', 'Soyosan'],
    ['동두천', 'Dongducheon'],
    ['보산', 'Bosan'],
    ['동두천중앙', 'Dongducheon Jungang', true],
    ['지행', 'Jihaeng'],
    ['덕정', 'Deokjeong'],
    ['덕계', 'Deokgye'],
    ['양주', 'Yangju'],
    ['녹양', 'Nogyang'],
    ['가능', 'Ganeung'],
    ['의정부', 'Uijeongbu'],
    ['회룡', 'Hoeryong'],
    ['망월사', 'Mangwolsa'],
    ['도봉산', 'Dobongsan'],
    ['도봉', 'Dobong'],
    ['방학', 'Banghak'],
    ['창동', 'Chang-dong', true],
    ['녹천', 'Nokcheon'],
    ['월계', 'Wolgye'],
    ['광운대', 'Kwangwoon Univ.', true],
    ['석계', 'Seokgye'],
    ['신이문', 'Sinimun'],
    ['외대앞', 'Hankuk Univ. of Foreign Studies', true],
    ['회기', 'Hoegi'],
    ['청량리', 'Cheongnyangni'],
    ['제기동', 'Jegi-dong', true],
    ['신설동', 'Sinseol-dong', true],
    ['동묘앞', 'Dongmyo', true],
    ['동대문', 'Dongdaemun'],
    ['종로5가', 'Jongno 5(o)-ga', true],
    ['종로3가', 'Jongno 3(sam)-ga', true],
    ['종각', 'Jonggak'],
    ['시청', 'City Hall', true],
    ['서울', 'Seoul'],
    ['남영', 'Namyeong'],
    ['용산', 'Yongsan'],
    ['노량진', 'Noryangjin'],
    ['대방', 'Daebang'],
    ['신길', 'Singil'],
    ['영등포', 'Yeongdeungpo'],
    ['신도림', 'Sindorim'],
    ['구로', 'Guro'],
    ['구일', 'Guil'],
    ['개봉', 'Gaebong'],
    ['오류동', 'Oryu-dong', true],
    ['온수', 'Onsu'],
    ['역곡', 'Yeokgok'],
    ['소사', 'Sosa'],
    ['부천', 'Bucheon'],
    ['중동', 'Jung-dong', true],
    ['송내', 'Songnae'],
    ['부개', 'Bugae'],
    ['부평', 'Bupyeong'],
    ['백운', 'Baegun'],
    ['동암', 'Dongam'],
    ['간석', 'Ganseok'],
    ['주안', 'Juan'],
    ['도화', 'Dohwa'],
    ['제물포', 'Jemulpo'],
    ['도원', 'Dowon'],
    ['동인천', 'Dongincheon'],
    ['인천', 'Incheon'],
    ['구로', 'Guro'],
    ['가산디지털단지', 'Gasan Digital Complex', true],
    ['독산', 'Doksan'],
    ['금천구청', 'Geumcheon-gu Office', true],
    ['석수', 'Seoksu'],
    ['관악', 'Gwanak'],
    ['안양', 'Anyang'],
    ['명학', 'Myeonghak'],
    ['금정', 'Geumjeong'],
    ['군포', 'Gunpo'],
    ['당정', 'Dangjeong'],
    ['의왕', 'Uiwang'],
    ['성균관대', 'Sungkyunkwan Univ.', true],
    ['화서', 'Hwaseo'],
    ['수원', 'Suwon'],
    ['세류', 'Seryu'],
    ['병점', 'Byeongjeom'],
    ['세마', 'Sema'],
    ['오산대', 'Osan College', true],
    ['오산', 'Osan'],
    ['진위', 'Jinwi'],
    ['송탄', 'Songtan'],
    ['서정리', 'Seojeong-ri', true],
    ['지제', 'Jije'],
    ['평택', 'Pyeongtaek'],
    ['성환', 'Seonghwan'],
    ['직산', 'Jiksan'],
    ['두정', 'Dujeong'],
    ['천안', 'Cheonan'],
    ['봉명', 'Bongmyeong'],
    ['쌍용', 'Ssangyong'],
    ['아산', 'Asan'],
    ['배방', 'Baebang'],
    ['온양온천', 'Onyangoncheon'],
    ['신창', 'Sinchang'],
    ['금천구청', 'Geumcheon-gu Office', true],
    ['광명', 'Gwangmyeong'],
    ['병점', 'Byeongjeom'],
    ['서동탄', 'Seodongtan']
];
$seoulLines[2] = [
    ['시청', 'City Hall', true],
    ['을지로입구', 'Euljiro 1-ga', true],
    ['을지로3가', 'Euljiro 3-ga', true],
    ['을지로4가', 'Euljiro 4-ga', true],
    ['동대문역사문화공원', 'Dongdaemun History & Culture Park', true],
    ['신당', 'Sindang'],
    ['상왕십리', 'Sangwangsimni'],
    ['왕십리', 'Wangsimni'],
    ['한양대', 'Hanyang University', true],
    ['뚝섬', 'Ttukseom'],
    ['성수', 'Seongsu'],
    ['건대입구', 'Konkuk University', true],
    ['구의', 'Guui'],
    ['강변', 'Gangbyeon'],
    ['잠실나루', 'Jamsillaru'],
    ['잠실', 'Jamsil'],
    ['신천', 'Sincheon'],
    ['종합운동장', 'Sports Complex', true],
    ['삼성', 'Samseong'],
    ['선릉', 'Seolleung'],
    ['역삼', 'Yeoksam'],
    ['강남', 'Gangnam'],
    ['교대', 'Seoul Nat\'l Univ. of Education', true],
    ['서초', 'Seocho'],
    ['방배', 'Bangbae'],
    ['사당', 'Sadang'],
    ['낙성대', 'Nakseongdae'],
    ['서울대입구', 'Seoul National University', true],
    ['봉천', 'Bongcheon'],
    ['신림', 'Sillim'],
    ['신대방', 'Sindaebang'],
    ['구로디지털단지', 'Guro Digital Complex', true],
    ['대림', 'Daerim'],
    ['신도림', 'Sindorim'],
    ['문래', 'Mullae'],
    ['영등포구청', 'Yeongdeungpo-gu Office', true],
    ['당산', 'Dangsan'],
    ['합정', 'Hapjeong'],
    ['홍대입구', 'Hongik University', true],
    ['신촌역 (지하)', 'Sinchon', true],
    ['이대', 'Ewha Woman\'s University', true],
    ['아현', 'Ahyeon'],
    ['충정로', 'Chungjeongno'],
    ['용답', 'Yongdap'],
    ['신답', 'Sindap'],
    ['용두', 'Yongdu'],
    ['신설동', 'Sinseol-dong', true],
    ['도림천', 'Dorimcheon'],
    ['양천구청', 'Yangcheon-gu Office', true],
    ['신정네거리', 'Sinjeongnegeori'],
    ['까치산', 'Kkachisan']
];
$seoulLines[3] = [
    ['대화', 'Daehwa'],
    ['주엽', 'Juyeop'],
    ['정발산', 'Jeongbalsan'],
    ['마두', 'Madu'],
    ['백석', 'Baekseok'],
    ['대곡', 'Daegok'],
    ['화정', 'Hwajeong'],
    ['원당', 'Wondang'],
    ['원흥', 'Wonheung'],
    ['삼송', 'Samsong'],
    ['지축', 'Jichuk'],
    ['구파발', 'Gupabal'],
    ['연신내', 'Yeonsinnae'],
    ['불광', 'Bulgwang'],
    ['녹번', 'Nokbeon'],
    ['홍제', 'Hongje'],
    ['무악재', 'Muakjae'],
    ['독립문', 'Dongnimmun'],
    ['경복궁', 'Gyeongbokgung'],
    ['안국', 'Anguk'],
    ['종로3가', 'Jongno 3(sam)-ga', true],
    ['을지로3가', 'Euljiro 3(sam)-ga', true],
    ['충무로', 'Chungmuro'],
    ['동대입구', 'Dongguk University', true],
    ['약수', 'Yaksu'],
    ['금호', 'Geumho'],
    ['옥수', 'Oksu'],
    ['압구정', 'Apgujeong'],
    ['신사', 'Sinsa'],
    ['잠원', 'Jamwon'],
    ['고속터미널', 'Express Bus Terminal', true],
    ['교대', 'Seoul Nat\'l Univ. of Education', true],
    ['남부터미널', 'Nambu Bus Terminal', true],
    ['양재', 'Yangjae'],
    ['매봉', 'Maebong'],
    ['도곡', 'Dogok'],
    ['대치', 'Daechi'],
    ['학여울', 'Hangnyeoul'],
    ['대청', 'Daecheong'],
    ['일원', 'Irwon'],
    ['수서', 'Suseo'],
    ['가락시장', 'Garak Market', true],
    ['경찰병원', 'National Police Hospital', true],
    ['오금', 'Ogeum']
];
